font="JetBrains Mono Nerd Font"

# anchor=center
# x-margin=0
# y-margin=0
# lines=15
# minimal-lines=no
# width=30
# tabs=8
horizontal-pad=28
vertical-pad=16
# inner-pad=0

[colors]
background=24273aff
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=74c7ecff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=74c7ecff
counter=7f849cff
border=cdd6f4ff

[border]
width=1
# radius=10

